config:
  theme: "red"
  size: 7

theme:

  blue: 
    - "000000"
    - "170e3f"
    - "191254"
    - "1a1769"
    - "1f1d86"
    - "2725a7"
    - "352dcd"
    - "493fd5"
    - "544fd8"
    - "6062dc"
    - "6d70df"
    - "7989e2"
    - "958ee6"
    - "b6a3eb"
    - "c9c0f1"
    - "fefbfb"
  
  cyan: 
    - "091a1b"
    - "122e36"
    - "163741"
    - "1c4c54"
    - "25696f"
    - "2d8683"
    - "37a49f"
    - "40bfbf"
    - "57c3c7"
    - "6ecacf"
    - "85d2d6"
    - "9cd7de"
    - "afe2e4"
    - "c6eaec"
    - "e4f6f6"
    - "fbfefe"
  
  dark: 
    - "000000"
    - "001418"
    - "002024"
    - "002c38"
    - "143444"
    - "443444"
    - "583c48"
    - "6c4c44"
    - "806058"
    - "6c706c"
    - "888078"
    - "a49484"
    - "c4ac9c"
    - "d8b0a8"
    - "ecd4d0"
    - "fcfcfc"

  dim: 
    - "313432"
    - "323e42"
    - "454b4b"
    - "3a5f3b"
    - "7c4545"
    - "675239"
    - "625055"
    - "516b43"
    - "796c64"
    - "718245"
    - "9e805c"
    - "998579"
    - "ac9086"
    - "a6a296"
    - "b4ab8f"
    - "bcb7a5"

  gold: 
    - "000000"
    - "0d0f05"
    - "131106"
    - "1f1b0a"
    - "2c2e0f"
    - "383d14"
    - "454918"
    - "50581d"
    - "6c6f25"
    - "82812b"
    - "889130"
    - "8fa136"
    - "a5c247"
    - "c2cd6a"
    - "bad685"
    - "fdfefb"

  natur: 
    - "0b0407"
    - "36122c"
    - "501b41"
    - "6f2566"
    - "8e2f84"
    - "8e38a8"
    - "7644c1"
    - "57a7c7"
    - "45bfb6"
    - "89c3a0"
    - "85d69d"
    - "a9de9c"
    - "c9e4af"
    - "e7ecc6"
    - "f5e9e0"
    - "fbf4f4"

  red: 
    - "000000"
    - "210720"
    - "2e0a2a"
    - "3f0e39"
    - "4f1147"
    - "601552"
    - "791b5b"
    - "97216f"
    - "b02779"
    - "c92c7a"
    - "d6438a"
    - "dd6499"
    - "e486aa"
    - "eeb0c1"
    - "f8dee3"
    - "fefefe"

  softfall: 
    - "ddcf99"
    - "cca87b"
    - "b97a60"
    - "9c524e"
    - "774251"
    - "4b3d44"
    - "4e5463"
    - "5b7d73"
    - "8e9f7d"
    - "645355"
    - "8c7c79"
    - "a99c8d"
    - "7d7b62"
    - "aaa25d"
    - "846d59"
    - "a88a5e"
